"""change detections create datetime

Revision ID: 22d9dbbafd65
Revises: 886f4960815a
Create Date: 2022-12-22 11:24:42.792461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d9dbbafd65'
down_revision = '886f4960815a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
