"""change detections

Revision ID: 26257749779a
Revises: 6a31faec54fd
Create Date: 2022-12-22 11:26:07.414540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26257749779a'
down_revision = '6a31faec54fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detections', 'create_datetime')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections', sa.Column('create_datetime', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
