"""change detections create datetime

Revision ID: 58da82662559
Revises: 22d9dbbafd65
Create Date: 2022-12-22 11:24:51.195257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58da82662559'
down_revision = '22d9dbbafd65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
