"""change detections create datetime

Revision ID: 886f4960815a
Revises: f6589e3add4f
Create Date: 2022-12-22 11:23:47.871793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886f4960815a'
down_revision = 'f6589e3add4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
