"""v.1

Revision ID: c4dcb110e3f7
Revises: e86e04d79ee0
Create Date: 2022-12-14 10:30:13.512527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4dcb110e3f7'
down_revision = 'e86e04d79ee0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.drop_constraint('answers_create_id_fkey', 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
    op.drop_column('answers', 'create_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('create_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key('answers_create_id_fkey', 'answers', 'users', ['create_id'], ['id'], ondelete='CASCADE')
    op.drop_column('answers', 'creator_id')
    # ### end Alembic commands ###
