"""initial

Revision ID: cb7df40cfee2
Revises: 
Create Date: 2022-12-11 23:09:40.833862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb7df40cfee2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracker_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('create_datetime', sa.DateTime(), nullable=True),
    sa.Column('imei_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['imei_id'], ['car_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracker_data')
    # ### end Alembic commands ###
