"""change detections

Revision ID: ee2162d4decc
Revises: 26257749779a
Create Date: 2022-12-22 11:26:18.302233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2162d4decc'
down_revision = '26257749779a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections', sa.Column('create_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detections', 'create_datetime')
    # ### end Alembic commands ###
